### ISSUE TITLE
Cache Ruleset panics when import

### ISSUE THREAD

**Issue by 7onn** [pulumi/pulumi-cloudflare#1006]
### Describe what happened

I'm on a task of covering CloudFlare configuration under IaC using Pulumi, and I have this block of code where I parse the `RulesetRule[]` out of an input yaml config file which crashes due to `panic: runtime error: invalid memory address or nil pointer dereference`. This is weird, as I'm imitating the current config values that I got from CloudFlare API and the config properties that I got from the [docs](https://www.pulumi.com/registry/packages/cloudflare/api-docs/ruleset/): 
```bash
# get rulesets
$ curl -s -X GET "https://api.cloudflare.com/client/v4/zones/<zone-id>/rulesets?per_page=200" -H "Authorization: Bearer <cloudflare-api-token>" -H "Content-Type: application/json" 
...
{
  "result": [
    {
      "description": "",
      "id": "5d85d2e2b1404e0fb6aa9cfd89aabe0d",
      "kind": "zone",
      "last_updated": "2024-12-03T13:29:35.474735Z",
      "name": "default",
      "phase": "http_request_cache_settings",
      "version": "76"
    },
  ]
}
...

# get rules
$ curl -s -X GET "https://api.cloudflare.com/client/v4/zones/<zone-id>/rulesets/5d85d2e2b1404e0fb6aa9cfd89aabe0d?per_page=200" -H "Authorization: Bearer <cloudflare-api-token>" -H "Content-Type: application/json" 
...
{
  "result": {
    "description": "",
    "id": "5d85d2e2b1404e0fb6aa9cfd89aabe0d",
    "kind": "zone",
    "last_updated": "2024-12-03T13:29:35.474735Z",
    "name": "default",
    "phase": "http_request_cache_settings",
    "rules": [
      {
        "action": "set_cache_settings",
        "action_parameters": {
          "cache": true,
          "edge_ttl": {
            "mode": "respect_origin",
            "status_code_ttl": [
              {
                "status_code_range": {
                  "from": 400,
                  "to": 599
                },
                "value": -1
              }
            ]
          }
        },
        "description": "Image Proxy CloudFront distribution",
        "enabled": true,
        "expression": "(http.host eq \"edge.example.com\") or (http.host eq \"edge-s.example.com\") or (http.host eq \"cache.example.com\")",
        "id": "5f4b97abd5104bdfbd10ed9803f6c42b",
        "last_updated": "2024-09-05T14:55:34.931444Z",
        "ref": "5f4b97abd5104bdfbd10ed9803f6c42b",
        "version": "43"
      },
```

This approach worked nicely for WAF rules and DNS records, but for cache rules, the provider panicked for some reason, which I cannot figure out why. I hope some help can come from this issue.

### Sample program

A configuration Pulumi.yaml like the following:
```yaml
name: cloudflare-domains
runtime: nodejs
description: Pulumi typescript code to manage CloudFlare infrastructure resources
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
environment:
  - staging
config:
  cloudflareZoneId: <zone-id>
  cacheRules:
  - description: "Image Proxy CloudFront distribution"
    action: "set_cache_settings"
    expression: (http.host eq "edge.example.com") or (http.host eq "edge-s.example.com") or (http.host eq "cache.example.com")
    actionParameters:
        cache: true
        edgeTtl:
          mode: "respect_origin"
          statusCodeTtls:
          - statusCodeRanges:
            - from: 400
              to: 599
            value: -1

  - description: "API"
    action: "set_cache_settings"
    expression: (http.host wildcard "api.example.com") and (http.request.uri.path contains "/templates/usecase/all" or http.request.uri.path contains "/templates/tags/groups/all")
    actionParameters:
        cache: true
        edgeTtl:
          mode: "respect_origin"
        browserTtl:
          default: 43200
          mode: "override_origin"

  - description: "Next image"
    action: "set_cache_settings"
    expression: (http.host eq "www.example.com" and http.request.uri.path eq "/_next/image") 
    actionParameters:
        cache: true
        serveStale: {}
        edgeTtl:
          default: 604800
          mode: "override_origin"
          statusCodeTtls:
          - statusCodeRanges:
            - from: 400
              to: 599
            value: -1

  - description: "CDN Full"
    action: "set_cache_settings"
    expression: (http.host eq "cdn.example.com") 
    actionParameters:
        cache: true
        edgeTtl:
          mode: "respect_origin"
          statusCodeTtls:
          - statusCodeRanges:
            - from: 400
              to: 599
            value: -1

  - description: "Bypass Cache for Tunnels"
    action: "set_cache_settings"
    expression: (http.host in {"xyz.example.com"})
    actionParameters:
        cache: false
```

A typescript program to parse the `cacheRules` property to `RulesetRule[]` and forward to my cache settings Ruleset.

```typescript
// ./src/cache.ts

import { Ruleset } from '@pulumi/cloudflare';
import { Config } from '@pulumi/pulumi';
import { cloudflareProvider as provider } from './provider';
import { RulesetRule } from '@pulumi/cloudflare/types/input';

export const createCacheRules = async () => {
  const pulumiConfig = new Config();
  const zoneId = pulumiConfig.require('cloudflareZoneId');
  const rules = pulumiConfig.requireObject('cacheRules') as RulesetRule[]

  new Ruleset(
  `ruleset/http_request_cache_settings`,
  {
    zoneId,
    rules,
    kind: 'zone',
    name: 'default',
    phase: 'http_request_cache_settings',
  },
  { 
    provider,
    import:
      "zone/<my-zone>/5d85d2e2b1404e0fb6aa9cfd89aabe0d"
  }
);
```

The app Pulumi app src/index.ts
```typescript
//import { createDnsRecords } from './records'
//import { createWAFRules } from  './waf'
import { createCacheRules } from './cache'

//createDnsRecords()
//createWAFRules()
createCacheRules()
```

The app package JSON.
```json
{
    "name": "cloudflare-domains",
    "version": "1.0.0",
    "main": "src/index.ts",
    "devDependencies": {
        "@types/node": "^18",
        "typescript": "^5.0.0"
    },
    "dependencies": {
        "@pulumi/cloudflare": "^5.45.0",
        "@pulumi/pulumi": "^3.143.0",
        "lint-staged": "^15.2.2",
        "zod": "^3.24.1"
    }
}
```

### Log output

```
 panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7409692]
    goroutine 135 [running]:
    github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.toRulesetResourceModel({0x8774bd8, 0xc001f24570}, {0x70?, {0xc0024f6d80?, 0xc0024f6d60?}}, {0x20?, {0x0?, 0x0?}}, {{0xc0006ea632, 0x20}, ...})
        /home/runner/work/pulumi-cloudflare/pulumi-cloudflare/upstream/internal/framework/service/rulesets/resource.go:627 +0x3cd2
    github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.(*RulesetResource).Read(0xc0010b0210, {0x8774bd8, 0xc001f24570}, {{{{0x8783818, 0xc001f85dd0}, {0x7fef580, 0xc001f84d50}}, {0x878d340, 0xc00118cff0}}, 0xc0010b0220, ...}, ...)
        /home/runner/work/pulumi-cloudflare/pulumi-cloudflare/upstream/internal/framework/service/rulesets/resource.go:206 +0x519
    github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0019466c8, {0x8774bd8, 0xc001f24570}, 0xc001f245a0, 0xc001fdb148)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.13.0/internal/fwserver/server_readresource.go:117 +0x84e
    github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0019466c8, {0x8774bd8?, 0xc00270cba0?}, 0xc000fc5640)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.13.0/internal/proto6server/server_readresource.go:55 +0x38e
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/tfbridge.(*provider).readResource(0xc000c26a88, {0x8774bd8, 0xc00270cba0}, 0xc001fdb3d0, 0x0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.1/pkg/pf/tfbridge/provider_read.go:151 +0x393
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/tfbridge.(*provider).importResource(0xc000c26a88, {0x8774bd8, 0xc00270cba0}, 0xc0000673d0, {0xc001d5e1e0, 0x46})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.1/pkg/pf/tfbridge/provider_read.go:266 +0x230
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/tfbridge.(*provider).ReadWithContext(0xc000c26a88, {0x8774bd8?, 0xc00270c720?}, {0xc001d60280, 0x79}, {0xc001d5e1e0, 0x46}, 0xc00270c780, 0xc00270c750)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.1/pkg/pf/tfbridge/provider_read.go:68 +0x268
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/internal/plugin.(*providerServer).Read(0xc0017d5b00, {0x8774bd8, 0xc00270c720}, 0xc00149c480)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.1/pkg/pf/internal/plugin/provider_server.go:421 +0x184
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/x/muxer.(*muxer).Read.func1({0x87982e0?, 0xc0017d5b00?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.1/pkg/x/muxer/muxer.go:382 +0x33
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/x/muxer.resourceMethod[...](0xc0011938c0?, 0x856ab20, 0xc0012836b8?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.1/pkg/x/muxer/muxer.go:335 +0xb5
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/x/muxer.(*muxer).Read(0xa01cef0?, {0x8774bd8?, 0xc00270c720?}, 0x7dfc980?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.1/pkg/x/muxer/muxer.go:381 +0x4a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x8774bd8?, 0xc00270c720?}, {0x84b8640?, 0xc00149c480?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.142.0/proto/go/provider_grpc.pb.go:833 +0xce
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x8774bd8, 0xc00270c450}, {0x84b8640, 0xc00149c480}, 0xc0016f44e0, 0xc0016f2750)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3c4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x86beb40, 0xc0011938c0}, {0x8774bd8, 0xc00270c450}, 0xc00149c400, 0xc00108ec80)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.142.0/proto/go/provider_grpc.pb.go:835 +0x143
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc001033800, {0x8774bd8, 0xc00270c3c0}, {0x8789000, 0xc0000d0b60}, 0xc0016a5440, 0xc0017d5b90, 0xa050950, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1394 +0xe2b
    google.golang.org/grpc.(*Server).handleStream(0xc001033800, {0x8789000, 0xc0000d0b60}, 0xc0016a5440)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1805 +0xe8b
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1029 +0x7f
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 43
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1040 +0x125

    error: preview failed
```

### Affected Resource(s)

Cloudflare Cache Ruleset

### Output of `pulumi about`

Here's my env info
```bash
$ pulumi about
...
CLI          
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       darwin
Version  14.6
Arch     x86_64

This project is written in nodejs: executable='/Users/tom/.nvm/versions/node/v18.20.5/bin/node' version='v18.20.5'

Current Stack: <org>/cloudflare-domains/example-com

TYPE                              URN
pulumi:pulumi:Stack               urn:pulumi:example-com::cloudflare-domains::pulumi:pulumi:Stack::cloudflare-domains-example-com
pulumi:providers:cloudflare       urn:pulumi:example-com::cloudflare-domains::pulumi:providers:cloudflare::cloudflare
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/opensearch-v2-metrics
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-imageproxy
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/vercel-frontend-preview
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-ses-dkim-2
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/vercel-frontend-cms-ui
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-objects.api
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-content
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-objects.cms
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-cdn.s
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/vercel-frontend-web
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/vercel-frontend-app
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-cdn-s
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-opensearch
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::A/vercel-frontend
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-ses-dkim-3
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/heroku-analytics-app
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-ses-dkim
cloudflare:index/ruleset:Ruleset  urn:pulumi:example-com::cloudflare-domains::cloudflare:index/ruleset:Ruleset::ruleset/http_request_firewall_custom
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/vercel-frontend-qa
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-image-proxy-s
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::TXT/amazon-ses
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-opensearch-v2-metrics
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-objects.api.development
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::TXT/aws-ses
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::TXT/google-site-verification
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-opensearch-v2
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::MX/smtp-from-amazon
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/opensearch-v2
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::TXT/domain-based-message-auth-reporting-and-conformance
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/vercel-frontend-qa-assignment
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/vercel-frontend-www
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-cdn
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/opensearch
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record-objects-cms-development
cloudflare:index/record:Record    urn:pulumi:example-com::cloudflare-domains::cloudflare:index/record:Record::CNAME/aws-acm-validation-record


Dependencies:
NAME                              VERSION
@types/node                       18.19.64
@typescript-eslint/eslint-plugin  7.18.0
@typescript-eslint/parser         7.18.0
eslint                            8.57.1
eslint-config-prettier            9.1.0
eslint-plugin-import              2.31.0
eslint-plugin-prettier            5.2.1
husky                             8.0.3
lint-staged                       15.2.10
prettier                          3.4.2
typescript                        5.6.3
typescript-eslint                 7.18.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
