### ISSUE TITLE
Can not destroy WorkersRoute resource

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-cloudflare#1130]
### Describe what happened

The WorkersRoute resource fails to destroy with an error message:

```
Diagnostics:
          cloudflare:index:WorkersRoute (workerRoute):
            error: failed to make http request: missing required route_id parameter
```

### Sample program

```yaml
runtime: yaml
name: workers-route
config:
  cloudflare-zone-id:
    type: string
  cloudflare-domain:
    type: string
resources:
  randomName:
    type: random:RandomString
    properties:
      length: 10
      numeric: false
      special: false
      upper: false
  workerRoute:
    type: cloudflare:WorkersRoute
    properties:
      zoneId: ${cloudflare-zone-id}
      pattern: "${cloudflare-domain}/${randomName.result}"

```

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
