### ISSUE TITLE
Issue with ruleset after upgrading to version 6.X

### ISSUE THREAD

**Issue by stian3555** [pulumi/pulumi-cloudflare#1164]
### Describe what happened

After upgrading to version 6.X of the pulumi-cloudflare provider, I encountered an error when running `pulumi preview`. The error message indicates a failure in encoding the rules property. Below is the relevant error 

```
Diagnostics:
  cloudflare:index:Ruleset (zonelevelmanagedwaf):
    error: objectEncoder failed on property "rules": encList failed while encoding element 0 ({map[action:{execute} actionParameters:{map[algorithms:{[]} autominifies:{[]} headers:{[]} id:{efb7b8c949ac4650a09736fc376e9aee} overrides:{map[categories:{[]} rules:{[{map[enabled:{true} id:{34583778093748cc83ff7b38f472013e}]}]}]} responses:{[]}]} description:{} enabled:{true} expression:{true} id:{e7687e51174f45b1b3785911caf58a2e} ref:{e7687e51174f45b1b3785911caf58a2e}]}): objectEncoder failed on property "action_parameters": objectEncoder failed on property "headers": Expected an Object PropertyValue, found [] ("{[]}")
```

### Sample program

```yaml
  zonelevelmanagedwaf:
    type: cloudflare:Ruleset
    properties:
      kind: zone
      name: default
      zoneId: ${zone.id}
      phase: http_request_firewall_managed
      rules:
        - action: execute
          actionParameters:
            id: efb7b8c949ac4650a09736fc376e9aee
            overrides:
              rules:
                - id: 34583778093748cc83ff7b38f472013e
                  enabled: true
          enabled: true
          expression: 'true'
        - action: execute
          actionParameters:
            id: 4814384a9e5d4991b9815dcfc25d2f1f
            overrides:
              categories:
                - category: paranoia-level-3
                  enabled: false
                - category: paranoia-level-4
                  enabled: false
              rules:
                - action: block
                  id: 6179ae15870a4bb7b2d480d4843b323c
                  scoreThreshold: 25
          enabled: true
          expression: 'true'
```

### Output of `pulumi about`

```
CLI          
Version      3.163.0
Go Version   go1.24.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  cloudflare  6.1.2
language  yaml        1.16.0

Host     
OS       darwin
Version  15.4.1
Arch     arm64

This project is written in yaml

...

Dependencies:
NAME        VERSION
cloudflare  6.1.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thanks for reprorting @stian3555 it sounds like we have a problem on the upgrade path. Since I do not see "headers" in your program this must be coming from the state allocated by the program on the previous version of the provider. You may be able to workaround by editing the state file `pulumi stack export/import` and removing the offending property. 

For us to fix the issue in the provider we need to introduce some state cleanup. It would be very helpful if you could attach a sample program before-and-after, and/or the relevant bits of the Pulumi state `pulumi stack export`.

**Comment by stian3555** [comment]
Thanks for responding so quick @t0yv0, I will look into using `pulumi stack export/import` to fix the issue :)

The Ruleset part of the config did not have to change after version 6, as far as I can understand from the documentation.

**Version 5.X**
```yaml
name: example-com
runtime: yaml
description: Domain example-com managed by Pulumi
variables: {}
resources:
  cloudflare-provider:
    type: pulumi:providers:cloudflare
    defaultProvider: true
    options:
      version: 5.49.1
  zone:
    type: cloudflare:Zone
    properties:
      accountId: 0123456789abcdef0123456789abcdef
      plan: enterprise
      type: full
      zone: example.com
  zonelevelmanagedwaf:
    type: cloudflare:Ruleset
    properties:
      kind: zone
      name: default
      zoneId: ${zone.id}
      phase: http_request_firewall_managed
      rules:
        - action: execute
          actionParameters:
            id: efb7b8c949ac4650a09736fc376e9aee
            overrides:
              rules:
                - id: 34583778093748cc83ff7b38f472013e
                  enabled: true
          enabled: true
          expression: "true"
        - action: execute
          actionParameters:
            id: 4814384a9e5d4991b9815dcfc25d2f1f
            overrides:
              categories:
                - category: paranoia-level-3
                  enabled: false
                - category: paranoia-level-4
                  enabled: false
              rules:
                - action: block
                  id: 6179ae15870a4bb7b2d480d4843b323c
                  scoreThreshold: 25
          enabled: true
          expression: "true"
```
**Version 6.X**
```yaml
name: example-com
runtime: yaml
description: Domain example-com managed by Pulumi
variables: {}
resources:
  cloudflare-provider:
    type: pulumi:providers:cloudflare
    defaultProvider: true
    options:
      version: 6.1.2
  zone:
    type: cloudflare:Zone
    properties:
      name: example.com
      account:
        id: 0123456789abcdef0123456789abcdef
  zonesubscription:
    type: cloudflare:ZoneSubscription
    properties:
      identifier: ${zone.id}
      ratePlan:
        id: enterprise
        scope: zone
  zonelevelmanagedwaf:
    type: cloudflare:Ruleset
    properties:
      kind: zone
      name: default
      zoneId: ${zone.id}
      phase: http_request_firewall_managed
      rules:
        - action: execute
          actionParameters:
            id: efb7b8c949ac4650a09736fc376e9aee
            overrides:
              rules:
                - id: 34583778093748cc83ff7b38f472013e
                  enabled: true
          enabled: true
          expression: "true"
        - action: execute
          actionParameters:
            id: 4814384a9e5d4991b9815dcfc25d2f1f
            overrides:
              categories:
                - category: paranoia-level-3
                  enabled: false
                - category: paranoia-level-4
                  enabled: false
              rules:
                - action: block
                  id: 6179ae15870a4bb7b2d480d4843b323c
                  scoreThreshold: 25
          enabled: true
          expression: "true"
```

Here is relevant output of `pulumi stack export`:

```json
{
    "resources": [
      {
        "urn": "urn:pulumi:prod::example-com::pulumi:pulumi:Stack::example-com-prod",
        "custom": false,
        "type": "pulumi:pulumi:Stack",
        "created": "2023-08-29T12:44:00.052052Z",
        "modified": "2023-08-29T12:44:00.052052Z"
      },
      {
        "urn": "urn:pulumi:prod::example-com::pulumi:providers:cloudflare::cloudflare-provider",
        "custom": true,
        "id": "2e1afd58-6c8f-477e-975d-0d9074000844",
        "type": "pulumi:providers:cloudflare",
        "inputs": {
          "__internal": {},
          "apiClientLogging": "false",
          "maxBackoff": "30",
          "minBackoff": "1",
          "retries": "3",
          "rps": "4",
          "version": "5.49.1"
        },
        "outputs": {
          "apiClientLogging": "false",
          "maxBackoff": "30",
          "minBackoff": "1",
          "retries": "3",
          "rps": "4",
          "version": "5.49.1"
        },
        "parent": "urn:pulumi:prod::example-com::pulumi:pulumi:Stack::example-com-prod",
        "additionalSecretOutputs": [
          "apiKey",
          "apiToken",
          "apiUserServiceKey"
        ],
        "created": "2025-04-24T06:45:36.773406689Z",
        "modified": "2025-04-24T06:45:36.773406689Z"
      },
      {
        "urn": "urn:pulumi:prod::example-com::cloudflare:index/zone:Zone::zone",
        "custom": true,
        "id": "00112233445566778899aabbccddeeff",
        "type": "cloudflare:index/zone:Zone",
        "inputs": {
          "__defaults": [],
          "accountId": "0123456789abcdef0123456789abcdef",
          "paused": false,
          "plan": "enterprise",
          "type": "full",
          "zone": "example.com"
        },
        "outputs": {
          "accountId": "0123456789abcdef0123456789abcdef",
          "id": "00112233445566778899aabbccddeeff",
          "meta": {
            "phishing_detected": false,
            "wildcard_proxiable": false
          },
          "nameServers": [
            "bob.ns.cloudflare.com",
            "lola.ns.cloudflare.com"
          ],
          "paused": false,
          "plan": "enterprise",
          "status": "active",
          "type": "full",
          "vanityNameServers": [],
          "verificationKey": "",
          "zone": "example.com"
        },
        "parent": "urn:pulumi:prod::example-com::pulumi:pulumi:Stack::example-com-prod",
        "protect": true,
        "provider": "urn:pulumi:prod::example-com::pulumi:providers:cloudflare::cloudflare-provider::2e1afd58-6c8f-477e-975d-0d9074000844",
        "propertyDependencies": {
          "accountId": [],
          "paused": [],
          "plan": [],
          "type": [],
          "zone": []
        },
        "created": "2023-08-29T12:44:02.1999Z",
        "modified": "2023-12-06T10:08:48.138224262Z"
      },
      {
        "urn": "urn:pulumi:prod::example-com::cloudflare:index/ruleset:Ruleset::zonelevelmanagedwaf",
        "custom": true,
        "id": "21b323bb1b7f438dacb65c6d3535c1e8",
        "type": "cloudflare:index/ruleset:Ruleset",
        "inputs": {
          "kind": "zone",
          "name": "default",
          "phase": "http_request_firewall_managed",
          "rules": [
            {
              "action": "execute",
              "actionParameters": {
                "id": "efb7b8c949ac4650a09736fc376e9aee",
                "overrides": {
                  "rules": [
                    {
                      "enabled": true,
                      "id": "34583778093748cc83ff7b38f472013e"
                    }
                  ]
                }
              },
              "enabled": true,
              "expression": "true"
            },
            {
              "action": "execute",
              "actionParameters": {
                "id": "4814384a9e5d4991b9815dcfc25d2f1f",
                "overrides": {
                  "categories": [
                    {
                      "category": "paranoia-level-3",
                      "enabled": false
                    },
                    {
                      "category": "paranoia-level-4",
                      "enabled": false
                    }
                  ],
                  "rules": [
                    {
                      "action": "block",
                      "id": "6179ae15870a4bb7b2d480d4843b323c",
                      "scoreThreshold": 25
                    }
                  ]
                }
              },
              "enabled": true,
              "expression": "true"
            }
          ],
          "zoneId": "00112233445566778899aabbccddeeff"
        },
        "outputs": {
          "__meta": "{\"schema_version\":\"1\"}",
          "description": "",
          "id": "21b323bb1b7f438dacb65c6d3535c1e8",
          "kind": "zone",
          "name": "default",
          "phase": "http_request_firewall_managed",
          "rules": [
            {
              "action": "execute",
              "actionParameters": {
                "algorithms": [],
                "autominifies": [],
                "headers": [],
                "id": "efb7b8c949ac4650a09736fc376e9aee",
                "overrides": {
                  "categories": [],
                  "rules": [
                    {
                      "enabled": true,
                      "id": "34583778093748cc83ff7b38f472013e"
                    }
                  ]
                },
                "responses": []
              },
              "description": "",
              "enabled": true,
              "expression": "true",
              "id": "e7687e51174f45b1b3785911caf58a2e",
              "ref": "e7687e51174f45b1b3785911caf58a2e"
            },
            {
              "action": "execute",
              "actionParameters": {
                "algorithms": [],
                "autominifies": [],
                "headers": [],
                "id": "4814384a9e5d4991b9815dcfc25d2f1f",
                "overrides": {
                  "categories": [
                    {
                      "category": "paranoia-level-3",
                      "enabled": false
                    },
                    {
                      "category": "paranoia-level-4",
                      "enabled": false
                    }
                  ],
                  "rules": [
                    {
                      "action": "block",
                      "id": "6179ae15870a4bb7b2d480d4843b323c",
                      "scoreThreshold": 25
                    }
                  ]
                },
                "responses": []
              },
              "description": "",
              "enabled": true,
              "expression": "true",
              "id": "9db92c3b92554eea81769eb5dc75df72",
              "ref": "9db92c3b92554eea81769eb5dc75df72"
            }
          ],
          "zoneId": "00112233445566778899aabbccddeeff"
        },
        "parent": "urn:pulumi:prod::example-com::pulumi:pulumi:Stack::example-com-prod",
        "dependencies": [
          "urn:pulumi:prod::example-com::cloudflare:index/zone:Zone::zone"
        ],
        "provider": "urn:pulumi:prod::example-com::pulumi:providers:cloudflare::cloudflare-provider::2e1afd58-6c8f-477e-975d-0d9074000844",
        "propertyDependencies": {
          "kind": [],
          "name": [],
          "phase": [],
          "rules": [],
          "zoneId": [
            "urn:pulumi:prod::example-com::cloudflare:index/zone:Zone::zone"
          ]
        },
        "created": "2024-04-16T12:58:54.826724Z",
        "modified": "2025-03-24T08:38:41.351673721Z"
      }
    ]
  }
```
