### ISSUE TITLE
It seems that the `apiClientLogging` property can no longer be passed to the provider in YAML

### ISSUE THREAD

**Issue by yuripallada-groupm** [pulumi/pulumi-cloudflare#1181]
File: [themes/default/content//registry/packages/cloudflare](https://www.pulumi.com/registry/packages/installation-configuration/)

We have this code:
```
  cloudflare-provider:
    type: pulumi:providers:cloudflare
    properties:
      apiToken: ${token}
      apiClientLogging: true
```

When we try to apply this using our pipeline, Pulumi shows this error:
```
Error: Property apiClientLogging does not exist on 'pulumi:providers:cloudflare'
  on Pulumi.yaml line 19:
  19:       apiClientLogging: true
Cannot assign '{apiToken: Invalid, apiClientLogging: boolean}' to 'pulumi:providers:cloudflare':
  Existing properties are: apiToken, apiKey, apiUserServiceKey, email, baseUrl and 1 other
```

The page: https://www.pulumi.com/registry/packages/cloudflare/installation-configuration/ Still shows this property as being a valid configuration parameter
