### ISSUE TITLE
Problem with ZoneSetting

### ISSUE THREAD

**Issue by stian3555** [pulumi/pulumi-cloudflare#1211]
### Describe what happened

As ZoneSettingsOverride is discontinued in provider version 6.x, I'm trying to migrate to ZoneSetting instead, but get the error when running `pulumi preview`:

`error: [pf/tfbridge] Error calling NewRawState: AttributeName("value"): DynamicPseudoType is not yet supported`

### Sample program

```yaml
name: example-com 
runtime: yaml
description: Manage zones and records belong to example.com domain
variables: {}
resources:
  cloudflare-provider:
    type: pulumi:providers:cloudflare
    defaultProvider: true
    options:
      version: 6.2.0
  zone:
    type: cloudflare:Zone
    properties:
      name: example.com
      account:
        id: 
  alwaysusehttps:
    type: cloudflare:ZoneSetting
    properties:
      settingId: always_use_https
      value: on
      zoneId: ${zone.id}
  mintlsversion:
    type: cloudflare:ZoneSetting
    properties:
      settingId: min_tls_version
      value: '1.2'
      zoneId: ${zone.id}
  tls13:
    type: cloudflare:ZoneSetting
    properties:
      settingId: tls_1_3
      value: on
      zoneId: ${zone.id}
  ssl:
    type: cloudflare:ZoneSetting
    properties:
      settingId: ssl
      value: strict
      zoneId: ${zone.id}
  securitylevel:
    type: cloudflare:ZoneSetting
    properties:
      settingId: security_level
      value: medium
      zoneId: ${zone.id}
```

### Log output

```
  cloudflare:index:ZoneSetting (alwaysusehttps):
    error: [pf/tfbridge] Error calling NewRawState: AttributeName("value"): DynamicPseudoType is not yet supported
```

### Affected Resource(s)

- ZoneSetting

### Output of `pulumi about`

```
CLI          
Version      3.170.0
Go Version   go1.24.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  cloudflare  6.2.0
language  yaml        1.19.0

Host     
OS       darwin
Version  15.5
Arch     arm64

This project is written in yaml

Dependencies:
NAME        VERSION
cloudflare  6.2.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
