### ISSUE TITLE
Change record type of existing name can't be done in one `up`

### ISSUE THREAD

**Issue by o-l-a-v** [pulumi/pulumi-cloudflare#687]
### What happened?

Changing record type, say A to CNAME, for an existing name, can't be done in one step.

Example YAML before (section from full file):

```yaml
  dev-a:
    type: cloudflare:Record
    properties:
      name: dev
      proxied: true
      type: A
      ttl: 1
      tags:
        - creationdate:2024-03-20
      value: 1.2.3.4
      zoneId: ${zone.id}
```

Example YAML after (section from full file):

```yaml
  dev-cname:
    type: cloudflare:Record
    properties:
      name: dev
      proxied: true
      type: CNAME
      ttl: 1
      tags:
        - creationdate:2024-03-20
      value: some.azurewebsites.net.
      zoneId: ${zone.id}
```

Pulumi `preview` will say that one record will be deleted, and one will be added. `up` will fail with:

```
cloudflare:index:Record (dev-cname):
  error: 1 error occurred:
     * expected DNS record to not already be present but already exists
```

Workaround 1:

* Delete existing record first -> `pulumi up`.
* Then add new record with the changed type -> `pulumi up`.

Workaround 2:

* Change record type and add non-default `priority` -> `pulumi up`.
* Remove `priority` -> `pulumi up`.

### Example

See "What happened?".

### Output of `pulumi about`

GitHub Actions
ubuntu-latest
pulumi/actions@v5
Pulumi CLI version 3.109.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @o-l-a-v. Sorry about that. To avoid downtime, pulumi implements tries to create the replacement record before removing the old one. This mostly works great, but causes errors like this for resources where the input properties specify a globally unique resource (like `cloudflare:Record`).

As a workaround, you can specify https://www.pulumi.com/docs/concepts/options/deletebeforereplace/. That should allow you to change the record in a single `pulumi up`.

**Comment by o-l-a-v** [comment]
I don't know if I see this issue as fixed. Maybe you should hint about this possible setting override in the error output or something?

**Comment by iwahbe** [comment]
It was fixed by https://github.com/pulumi/pulumi-cloudflare/pull/693, which will set the override for you for this resource.

**Comment by o-l-a-v** [comment]
Aha, sweet. Sorry I didn't catch that.

**Comment by o-l-a-v** [comment]
@iwahbe 

How do you set this attribute manually? I first tried:

```yaml
...
  root-A:
    type: cloudflare:Record
    options:
      deleteBeforeReplace: true
    properties:      
      name: "@"
      proxied: true
      ttl: 1
      type: A
      value: 192.0.2.1
      zoneId: ${zone.id}
...
```

I then tried to put in under properties like so:

```yaml
...
  root-A:
    type: cloudflare:Record
    properties:
      deleteBeforeReplace: true
      name: "@"
      proxied: true
      ttl: 1
      type: A
      value: 192.0.2.1
      zoneId: ${zone.id}
...
```

But then pulumi preview failed and said that property does not exist.
